/* select USER_ID,
USERNAME, CREATED,PASSWORD_CHANGE_DATE from the USER_USERS */

select USER_ID,  
       USERNAME,   
       CREATED,  
       PASSWORD_CHANGE_DATE 
from USER_USERS;

:select * from USER_TABLES;

describe orders

select * from PRODUCTLIST;

select * from REVIEWS;

select * from STOREFRONT;

select * from USERBASE;

select * from USERLIBRARY;

SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'ORDERS';

-- Describe the PRODUCTLIST table
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'PRODUCTLIST';

-- Describe the REVIEWS table
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'REVIEWS';

-- Describe the STOREFRONT table
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'STOREFRONT';

-- Describe the USERBASE table
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'USERBASE';

-- Describe the USERLIBRARY table
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'USERLIBRARY';

SELECT * FROM ORDERS;
-- Display everything in the PRODUCTLIST table

SELECT * FROM PRODUCTLIST;
-- Display everything in the REVIEWS table

SELECT * FROM REVIEWS;
-- Display everything in the STOREFRONT table

SELECT * FROM STOREFRONT;
-- Display everything in the USERBASE table

SELECT * FROM USERBASE;
-- Display everything in the USERLIBRARY table

SELECT * FROM USERLIBRARY;

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS

FROM USER_CONSTRAINTS;

SELECT VIEW_NAME, TEXT

FROM USER_VIEWS;

SELECT VIEW_NAME, TEXT

FROM USER_VIEWS;

SELECT FIRSTNAME, LASTNAME, USERNAME, PASSWORD, EMAIL
FROM USERBASE
WHERE EMAIL LIKE '%@yahoo.com';

SELECT USERID, PRODUCTCODE
FROM USERLIBRARY
WHERE HOURSPLAYED > 100;

SELECT DISTINCT PUBLISHER
FROM PRODUCTLIST;

SELECT PRODUCTNAME, RELEASEDATE, PUBLISHER, GENRE
FROM PRODUCTLIST
ORDER BY GENRE;

SELECT PRODUCTCODE, PUBLISHER
FROM PRODUCTLIST
WHERE GENRE = 'Strategy';



:
